# Generated by Django 4.2.1 on 2023-10-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_info', '0002_whislist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedBack',
        ),
    ]
