# Generated by Django 4.2.1 on 2023-10-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_info', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
