# Generated by Django 4.2.1 on 2023-10-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_recipes_ingredients_alter_recipes_intro_and_more'),
        ('chef_info', '0005_remove_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_new',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateField()),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('chef_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.chef')),
            ],
        ),
    ]
